### PR TITLE
Various fixes: notification panel wrap, min lock amount (#628), remove "no tokens" alert on exchange (#604), 

### LINKED ISSUE #604: how to get auer box is not needed on exchange fiat page
Screenshot_20190501-121014_Trust Wallet

### LINKED ISSUE #628: new lock page: lock product properties mismatched (minimumLockAmount)
Selecting different lock products from the dropdown does not update the minimum amount.

Steps to reproduce (rinkeby):
- Go to "New lock" page
- Select the "Lock for an hour" product (minimumLockAmount: 20)
- (A) Enter 5 into the amount field: an incorrect message is shown: "Minimum lockable amount is 10 A-EUR for selected lock term", however the actual minimum for this product is 20
- (B) Enter 15 into the amount field: the minimum check is incorrect - it checks for the wrong minimum (10 instead of 20): the invalid transaction is sent, and it will fail.

Seems like the minimum of the first lock product is stuck, and does not get updated when selecting another product.

### PR DESCRIPTION
**Pull request by brigittaforrai**
#### Nature of the PR: bug

fixes #628 
fixes #604
fixes : notification panel

#### Is connection necessary to test? If so which network?
- [ x] local RPC
- [x ] Rinkeby
- [x ] Main Ethereum Network

### CODE REVIEW

**Comment by szerintedmi** [comment]
Deploy preview for *augmint* processing.

Building with commit 69d3964bf7be9d821a21ba9b6b64b91860a38fbe

https://app.netlify.com/sites/augmint/deploys/5ce529fcd3067d00081fbab1

File: src/containers/app/EthereumTxStatus.js [hunk 1]
```diff
@@ -115,7 +115,8 @@ class EthereumTxStatus extends React.Component {
                                 <p>To be repaid: {repaymentAmount} A-EUR</p>
                                 <p>Collateral in escrow: {collateralEth} ETH</p>
                                 <p>
-                                    Loan id: {vals.loanId} | Product id: {vals.productId} | borrower: {vals.borrower}
+                                    Loan id: {vals.loanId} | Product id: {vals.productId} | borrower:{" "}
+                                    <span className="small">{vals.borrower}</span>
```
Comment (rszaloki) [inline src/containers/app/EthereumTxStatus.js]: please, move the whitespace into the span

Comment (brigittaforrai) [reply src/containers/app/EthereumTxStatus.js]: done
