### PR TITLE
fix: spurious "Show older" button on Exchange

### LINKED ISSUE #626: Exchange: spurious "Show older" button
showmore

### PR DESCRIPTION
**Pull request by ejulcsi**
Fixes #626

### CODE REVIEW

**Comment by szerintedmi** [comment]
Deploy preview for *augmint* processing.

Building with commit f674da165c85cf23aa2430bf21d7ab0eb2268d49

https://app.netlify.com/sites/augmint/deploys/5cd559d402ba4e000747a8e4

File: src/containers/account/components/TransferList.js [hunk 1]
```diff
@@ -152,7 +152,7 @@ class TransferList extends React.Component {
                         </StyleTable>
                     </div>
                 )}
-                {transfers && !this.isLastPage() && (
+                {transfers && transfers.length > 0 && !this.isLastPage() && (
```
Comment (phraktle) [inline src/containers/account/components/TransferList.js]: this breaks account history. if you had no transactions in the past 30 days (ie. the first loaded batch), the button is not shown thus there's no way to see your history.
